version: "3.7"

services:
  p7webapp.api:
    image: ${DOCKER_REGISTRY-}p7webappapi
    env_file:
      - .env
    build:
      context: ../
      dockerfile: ./P7WebApp.API/Dockerfile
      target: ${TARGET_RUN_CONFIG}
    expose:
      - "5000"
    restart: always
    depends_on:
      - p7webapp.ui


  p7webapp.ui:
    image: p7webappui
    env_file:
      - .env
    container_name: p7webapp_ui
    build:
      context: ../
      dockerfile: ./P7WebApp.webui/Dockerfile
      target: ${TARGET_RUN_CONFIG}
    volumes:
      - type: bind
        source: ../p7webapp.webui
        target: /app
    ports:
      - "80:80"
    restart: always
  
  postgres:
    image: postgres:14.5
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TARGET_USER}
      - POSTGRES_PASSWORD=${TARGET_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - /var/lib/docker/volumes/postgres/_data:/var/lib/postgresql/data