version: "3.7"

services:
  p7webapp.api-PROD:
    image: p7webappapi-prod
    container_name: p7webapp.api-PROD
    env_file:
      - .env
    build:
      context: ../
      dockerfile: ./P7WebApp.API/Dockerfile
      target: production
    expose:
      - "5000"
    restart: always
    depends_on:
      - p7webapp.ui-PROD


  p7webapp.ui-PROD:
    image: p7webappui-prod
    env_file:
      - .env
    container_name: p7webapp_ui_PROD
    build:
      context: ../
      dockerfile: ./P7WebApp.webui/Dockerfile
      target: production
    volumes:
      - type: bind
        source: ../p7webapp.webui
        target: /app
    ports:
      - "80:80"
    restart: always
  

  postgres-PROD:
    image: postgres:14.5
    container_name: postgres_db_PROD
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TARGET_USER}
      - POSTGRES_PASSWORD=${TARGET_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker/volumes/postgres/_data:/var/lib/postgresql/data