export const dummyData =[{
  "id": 1,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 37,
  "Members": 23,
  "Owner": "Emma"
}, {
  "id": 2,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 45,
  "Members": 23,
  "Owner": "Allistir"
}, {
  "id": 3,
  "Course_name": "Business Development (BS)",
  "Exercises": 96,
  "Members": 77,
  "Owner": "Neille"
}, {
  "id": 4,
  "Course_name": "Product Management (PM)",
  "Exercises": 84,
  "Members": 57,
  "Owner": "Rubie"
}, {
  "id": 5,
  "Course_name": "Engineering",
  "Exercises": 96,
  "Members": 35,
  "Owner": "Robinette"
}, {
  "id": 6,
  "Course_name": "Engineering",
  "Exercises": 28,
  "Members": 20,
  "Owner": "Allissa"
}, {
  "id": 7,
  "Course_name": "Legal",
  "Exercises": 86,
  "Members": 78,
  "Owner": "Roxi"
}, {
  "id": 8,
  "Course_name": "Training",
  "Exercises": 92,
  "Members": 87,
  "Owner": "Chancey"
}, {
  "id": 9,
  "Course_name": "Engineering",
  "Exercises": 21,
  "Members": 41,
  "Owner": "Dolores"
}, {
  "id": 10,
  "Course_name": "Engineering",
  "Exercises": 30,
  "Members": 10,
  "Owner": "Chryste"
}, {
  "id": 11,
  "Course_name": "Marketing",
  "Exercises": 46,
  "Members": 23,
  "Owner": "Barney"
}, {
  "id": 12,
  "Course_name": "Engineering",
  "Exercises": 63,
  "Members": 80,
  "Owner": "Adina"
}, {
  "id": 13,
  "Course_name": "Training",
  "Exercises": 77,
  "Members": 41,
  "Owner": "Krystalle"
}, {
  "id": 14,
  "Course_name": "Services",
  "Exercises": 91,
  "Members": 90,
  "Owner": "Silvano"
}, {
  "id": 15,
  "Course_name": "Services",
  "Exercises": 45,
  "Members": 23,
  "Owner": "Reider"
}, {
  "id": 16,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 15,
  "Members": 42,
  "Owner": "Yul"
}, {
  "id": 17,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 97,
  "Members": 27,
  "Owner": "Susette"
}, {
  "id": 18,
  "Course_name": "Research and Development",
  "Exercises": 18,
  "Members": 52,
  "Owner": "Eyde"
}, {
  "id": 19,
  "Course_name": "Engineering",
  "Exercises": 20,
  "Members": 54,
  "Owner": "Lyn"
}, {
  "id": 20,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 38,
  "Members": 30,
  "Owner": "Rainer"
}, {
  "id": 21,
  "Course_name": "Business Development (BS)",
  "Exercises": 18,
  "Members": 77,
  "Owner": "Dene"
}, {
  "id": 22,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 65,
  "Members": 49,
  "Owner": "Grange"
}, {
  "id": 23,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 11,
  "Members": 85,
  "Owner": "Aggy"
}, {
  "id": 24,
  "Course_name": "Business Development (BS)",
  "Exercises": 70,
  "Members": 17,
  "Owner": "Rasla"
}, {
  "id": 25,
  "Course_name": "Business Development (BS)",
  "Exercises": 27,
  "Members": 8,
  "Owner": "Hillie"
}, {
  "id": 26,
  "Course_name": "Research and Development",
  "Exercises": 30,
  "Members": 86,
  "Owner": "Fiona"
}, {
  "id": 27,
  "Course_name": "Sales",
  "Exercises": 22,
  "Members": 21,
  "Owner": "Addie"
}, {
  "id": 28,
  "Course_name": "Training",
  "Exercises": 76,
  "Members": 93,
  "Owner": "Mack"
}, {
  "id": 29,
  "Course_name": "Training",
  "Exercises": 61,
  "Members": 56,
  "Owner": "Sebastian"
}, {
  "id": 30,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 90,
  "Members": 19,
  "Owner": "Eduino"
}, {
  "id": 31,
  "Course_name": "Services",
  "Exercises": 71,
  "Members": 18,
  "Owner": "Barby"
}, {
  "id": 32,
  "Course_name": "Training",
  "Exercises": 6,
  "Members": 43,
  "Owner": "Robinia"
}, {
  "id": 33,
  "Course_name": "Human Resources",
  "Exercises": 64,
  "Members": 55,
  "Owner": "Phelia"
}, {
  "id": 34,
  "Course_name": "Business Development (BS)",
  "Exercises": 66,
  "Members": 79,
  "Owner": "Ardisj"
}, {
  "id": 35,
  "Course_name": "Research and Development",
  "Exercises": 55,
  "Members": 45,
  "Owner": "Joshia"
}, {
  "id": 36,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 36,
  "Members": 98,
  "Owner": "Randolph"
}, {
  "id": 37,
  "Course_name": "Sales",
  "Exercises": 73,
  "Members": 51,
  "Owner": "Magnum"
}, {
  "id": 38,
  "Course_name": "Human Resources",
  "Exercises": 21,
  "Members": 55,
  "Owner": "Persis"
}, {
  "id": 39,
  "Course_name": "Research and Development",
  "Exercises": 96,
  "Members": 61,
  "Owner": "Sephira"
}, {
  "id": 40,
  "Course_name": "Training",
  "Exercises": 91,
  "Members": 62,
  "Owner": "Ernie"
}, {
  "id": 41,
  "Course_name": "Human Resources",
  "Exercises": 32,
  "Members": 61,
  "Owner": "Vittoria"
}, {
  "id": 42,
  "Course_name": "Training",
  "Exercises": 16,
  "Members": 15,
  "Owner": "Lindsy"
}, {
  "id": 43,
  "Course_name": "Product Management (PM)",
  "Exercises": 88,
  "Members": 83,
  "Owner": "Pansie"
}, {
  "id": 44,
  "Course_name": "Sales",
  "Exercises": 23,
  "Members": 63,
  "Owner": "Elfie"
}, {
  "id": 45,
  "Course_name": "Human Resources",
  "Exercises": 72,
  "Members": 7,
  "Owner": "Enriqueta"
}, {
  "id": 46,
  "Course_name": "Product Management (PM)",
  "Exercises": 38,
  "Members": 37,
  "Owner": "Amos"
}, {
  "id": 47,
  "Course_name": "Research and Development",
  "Exercises": 4,
  "Members": 34,
  "Owner": "Nealson"
}, {
  "id": 48,
  "Course_name": "Training",
  "Exercises": 2,
  "Members": 34,
  "Owner": "Rawley"
}, {
  "id": 49,
  "Course_name": "Business Development (BS)",
  "Exercises": 8,
  "Members": 86,
  "Owner": "Marissa"
}, {
  "id": 50,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 9,
  "Members": 67,
  "Owner": "Taite"
}, {
  "id": 51,
  "Course_name": "Sales",
  "Exercises": 56,
  "Members": 80,
  "Owner": "Wake"
}, {
  "id": 52,
  "Course_name": "Human Resources",
  "Exercises": 80,
  "Members": 30,
  "Owner": "Gloriana"
}, {
  "id": 53,
  "Course_name": "Engineering",
  "Exercises": 64,
  "Members": 35,
  "Owner": "Moise"
}, {
  "id": 54,
  "Course_name": "Human Resources",
  "Exercises": 23,
  "Members": 20,
  "Owner": "Dierdre"
}, {
  "id": 55,
  "Course_name": "Engineering",
  "Exercises": 10,
  "Members": 99,
  "Owner": "Felita"
}, {
  "id": 56,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 14,
  "Members": 41,
  "Owner": "Nessy"
}, {
  "id": 57,
  "Course_name": "Training",
  "Exercises": 32,
  "Members": 45,
  "Owner": "Richart"
}, {
  "id": 58,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 24,
  "Members": 84,
  "Owner": "Arlyne"
}, {
  "id": 59,
  "Course_name": "Services",
  "Exercises": 91,
  "Members": 63,
  "Owner": "Ethelind"
}, {
  "id": 60,
  "Course_name": "Training",
  "Exercises": 29,
  "Members": 5,
  "Owner": "Allister"
}, {
  "id": 61,
  "Course_name": "Human Resources",
  "Exercises": 7,
  "Members": 64,
  "Owner": "Marika"
}, {
  "id": 62,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 48,
  "Members": 31,
  "Owner": "Andy"
}, {
  "id": 63,
  "Course_name": "Training",
  "Exercises": 71,
  "Members": 89,
  "Owner": "Ferrel"
}, {
  "id": 64,
  "Course_name": "Business Development (BS)",
  "Exercises": 33,
  "Members": 18,
  "Owner": "Nanny"
}, {
  "id": 65,
  "Course_name": "Human Resources",
  "Exercises": 51,
  "Members": 15,
  "Owner": "Hebert"
}, {
  "id": 66,
  "Course_name": "Legal",
  "Exercises": 48,
  "Members": 37,
  "Owner": "Lin"
}, {
  "id": 67,
  "Course_name": "Marketing",
  "Exercises": 89,
  "Members": 3,
  "Owner": "Pammie"
}, {
  "id": 68,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 90,
  "Members": 65,
  "Owner": "Aryn"
}, {
  "id": 69,
  "Course_name": "Services",
  "Exercises": 48,
  "Members": 20,
  "Owner": "Nettle"
}, {
  "id": 70,
  "Course_name": "Research and Development",
  "Exercises": 91,
  "Members": 34,
  "Owner": "Myra"
}, {
  "id": 71,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 69,
  "Members": 89,
  "Owner": "Stormie"
}, {
  "id": 72,
  "Course_name": "Research and Development",
  "Exercises": 44,
  "Members": 89,
  "Owner": "Maia"
}, {
  "id": 73,
  "Course_name": "Legal",
  "Exercises": 37,
  "Members": 8,
  "Owner": "Ruthi"
}, {
  "id": 74,
  "Course_name": "Programming Paradigms (PP)",
  "Exercises": 62,
  "Members": 52,
  "Owner": "Modesty"
}, {
  "id": 75,
  "Course_name": "Services",
  "Exercises": 1,
  "Members": 41,
  "Owner": "Caddric"
}, {
  "id": 76,
  "Course_name": "Sales",
  "Exercises": 81,
  "Members": 22,
  "Owner": "Alikee"
}, {
  "id": 77,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 76,
  "Members": 71,
  "Owner": "Garrick"
}, {
  "id": 78,
  "Course_name": "Training",
  "Exercises": 82,
  "Members": 11,
  "Owner": "Peri"
}, {
  "id": 79,
  "Course_name": "Research and Development",
  "Exercises": 85,
  "Members": 32,
  "Owner": "Morey"
}, {
  "id": 80,
  "Course_name": "Human Resources",
  "Exercises": 8,
  "Members": 74,
  "Owner": "Derrik"
}, {
  "id": 81,
  "Course_name": "Product Management (PM)",
  "Exercises": 13,
  "Members": 74,
  "Owner": "Erny"
}, {
  "id": 82,
  "Course_name": "Services",
  "Exercises": 14,
  "Members": 46,
  "Owner": "Eward"
}, {
  "id": 83,
  "Course_name": "Legal",
  "Exercises": 75,
  "Members": 2,
  "Owner": "Bridget"
}, {
  "id": 84,
  "Course_name": "Research and Development",
  "Exercises": 95,
  "Members": 30,
  "Owner": "Ettie"
}, {
  "id": 85,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 58,
  "Members": 57,
  "Owner": "Janifer"
}, {
  "id": 86,
  "Course_name": "Services",
  "Exercises": 52,
  "Members": 24,
  "Owner": "Caren"
}, {
  "id": 87,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 45,
  "Members": 61,
  "Owner": "Harald"
}, {
  "id": 88,
  "Course_name": "Product Management (PM)",
  "Exercises": 2,
  "Members": 42,
  "Owner": "Sada"
}, {
  "id": 89,
  "Course_name": "Object Oriented Programming (OOP)",
  "Exercises": 33,
  "Members": 10,
  "Owner": "Joseph"
}, {
  "id": 90,
  "Course_name": "Human Resources",
  "Exercises": 39,
  "Members": 9,
  "Owner": "Zara"
}, {
  "id": 91,
  "Course_name": "Legal",
  "Exercises": 59,
  "Members": 96,
  "Owner": "Theresa"
}, {
  "id": 92,
  "Course_name": "Training",
  "Exercises": 26,
  "Members": 33,
  "Owner": "Devinne"
}, {
  "id": 93,
  "Course_name": "Services",
  "Exercises": 33,
  "Members": 36,
  "Owner": "Glad"
}, {
  "id": 94,
  "Course_name": "Business Development (BS)",
  "Exercises": 78,
  "Members": 28,
  "Owner": "Mariele"
}, {
  "id": 95,
  "Course_name": "Services",
  "Exercises": 77,
  "Members": 13,
  "Owner": "Auria"
}, {
  "id": 96,
  "Course_name": "Human Resources",
  "Exercises": 8,
  "Members": 7,
  "Owner": "Vanna"
}, {
  "id": 97,
  "Course_name": "Marketing",
  "Exercises": 73,
  "Members": 47,
  "Owner": "Clarissa"
}, {
  "id": 98,
  "Course_name": "Business Development (BS)",
  "Exercises": 97,
  "Members": 85,
  "Owner": "Daryl"
}, {
  "id": 99,
  "Course_name": "Engineering",
  "Exercises": 98,
  "Members": 65,
  "Owner": "Erv"
}, {
  "id": 100,
  "Course_name": "Engineering",
  "Exercises": 67,
  "Members": 98,
  "Owner": "Leann"
}]