name: Test application

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./P7WebApp
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK '6.x'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore 
      - name: Build 
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal